spring:
  # 首页图标变更，关闭默认图标
  mvc:
    favicon:
      enabled: false
# 关闭模板引擎缓存
  thymeleaf:
    cache: false
# 国际化 我们的配置文件放在的真实位置
  messages:
    basename: i18n.login

# 配置路径localhost:8080/wecode/
server:
  servlet:
    context-path: /wecode
